window:
  #startup_mode: Fullscreen
  decorations: none
  padding:
    x: 10
    y: 10
  opacity: 0.8


font:
  size: 15

key_bindings:
  - { key: V, mods: Control, action: Paste}
  - { key: C, mods: Control, action: Copy}
